spring:
  datasource:
    url: jdbc:mysql://sab.cfaocwwyee44.us-east-1.rds.amazonaws.com/messaging_app
    username: atulchan
    password: 19031105
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.baomidou.mybatisplus: debug



